### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DRIPDROPS** [rsksmart/rif-relay-contracts#128]
npx hardhat collector:change-partners --collector-address "<0x9b91c655AaE10E6cd0a941Aa90A6e7aa97FB02F4" --partner-config "partner-shares.json" --gas-limit "200000" --network regtest

arrow still on address will confuse a newbie

**Comment by antomor** [comment]
@DRIPDROPS Thank you for the suggestion, just included the fix 👍🏼
